#!/usr/bin/env python3
"""
Caesar 3 PE binary reconnaissance script.

Usage: python3 pe_recon.py <path_to_caesar3.exe>

Analyzes PE headers, imports, sections, and compiler fingerprints.
Outputs findings to stdout (redirect to recon_report.md).
"""

import sys
import hashlib
import os

try:
    import pefile
    HAS_PEFILE = True
except ImportError:
    HAS_PEFILE = False
    print("[!] pefile not installed. Run: pip install pefile")


def file_hashes(filepath: str) -> dict:
    """Compute MD5, SHA1, SHA256 of the file."""
    md5 = hashlib.md5()
    sha1 = hashlib.sha1()
    sha256 = hashlib.sha256()

    with open(filepath, "rb") as f:
        while chunk := f.read(8192):
            md5.update(chunk)
            sha1.update(chunk)
            sha256.update(chunk)

    return {
        "md5": md5.hexdigest(),
        "sha1": sha1.hexdigest(),
        "sha256": sha256.hexdigest(),
        "size": os.path.getsize(filepath),
    }


def analyze_pe(filepath: str):
    """Full PE analysis."""
    if not HAS_PEFILE:
        print("[!] Cannot analyze PE without pefile module")
        return

    pe = pefile.PE(filepath)

    print("# Phase 1 — Binary Reconnaissance Report\n")
    print(f"> Generated by pe_recon.py\n")

    # File info
    hashes = file_hashes(filepath)
    print("## File Identification\n")
    print(f"| Property | Value |")
    print(f"|----------|-------|")
    print(f"| File | `{os.path.basename(filepath)}` |")
    print(f"| Size | {hashes['size']:,} bytes |")
    print(f"| MD5 | `{hashes['md5']}` |")
    print(f"| SHA1 | `{hashes['sha1']}` |")
    print(f"| SHA256 | `{hashes['sha256']}` |")
    print()

    # PE headers
    print("## PE Headers\n")
    print(f"| Property | Value |")
    print(f"|----------|-------|")
    print(f"| Machine | {hex(pe.FILE_HEADER.Machine)} ({'i386' if pe.FILE_HEADER.Machine == 0x14c else 'other'}) |")
    print(f"| Timestamp | {pe.FILE_HEADER.TimeDateStamp} |")
    print(f"| Subsystem | {pe.OPTIONAL_HEADER.Subsystem} ({'GUI' if pe.OPTIONAL_HEADER.Subsystem == 2 else 'Console'}) |")
    print(f"| Entry Point | {hex(pe.OPTIONAL_HEADER.AddressOfEntryPoint)} |")
    print(f"| Image Base | {hex(pe.OPTIONAL_HEADER.ImageBase)} |")
    print()

    # Sections
    print("## Sections\n")
    print(f"| Name | VirtualAddr | VirtualSize | RawSize | Entropy |")
    print(f"|------|------------|-------------|---------|---------|")
    text_size = 0
    for section in pe.sections:
        name = section.Name.decode("utf-8", errors="replace").rstrip("\x00")
        entropy = section.get_entropy()
        print(f"| {name} | {hex(section.VirtualAddress)} | {section.Misc_VirtualSize:,} | {section.SizeOfRawData:,} | {entropy:.2f} |")
        if ".text" in name:
            text_size = section.SizeOfRawData
    print()

    # Function estimate
    if text_size > 0:
        est_funcs = text_size // 50  # rough average function size
        print(f"## Function Count Estimate\n")
        print(f"- .text section size: {text_size:,} bytes")
        print(f"- Estimated functions (avg 50 bytes): ~{est_funcs}")
        print(f"- Estimated functions (avg 100 bytes): ~{text_size // 100}")
        print()

    # Imports
    print("## Import Table\n")
    if hasattr(pe, "DIRECTORY_ENTRY_IMPORT"):
        for entry in pe.DIRECTORY_ENTRY_IMPORT:
            dll_name = entry.dll.decode("utf-8", errors="replace")
            funcs = [imp.name.decode("utf-8", errors="replace")
                     for imp in entry.imports if imp.name]
            print(f"### {dll_name} ({len(funcs)} functions)\n")
            for f in sorted(funcs):
                print(f"- `{f}`")
            print()
    else:
        print("_No imports found_\n")

    # Exports
    print("## Export Table\n")
    if hasattr(pe, "DIRECTORY_ENTRY_EXPORT"):
        for exp in pe.DIRECTORY_ENTRY_EXPORT.symbols:
            print(f"- `{exp.name}`")
    else:
        print("_No exports (expected for .exe)_\n")

    # Compiler fingerprint hints
    print("## Compiler Fingerprinting\n")
    rich_header = pe.parse_rich_header()
    if rich_header:
        print("- **Rich header found** — indicates MSVC linker")
        print(f"- Rich header entries: {len(rich_header.get('values', []))}")
    else:
        print("- No Rich header — may indicate non-MSVC or stripped")

    pe.close()


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <path_to_binary>")
        sys.exit(1)

    filepath = sys.argv[1]
    if not os.path.exists(filepath):
        print(f"[!] File not found: {filepath}")
        sys.exit(1)

    analyze_pe(filepath)


if __name__ == "__main__":
    main()
